services:
  bcs-batighor:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./runtime:/app/runtime
      - ./config:/app/config
    restart: unless-stopped
